#!/usr/bin/env python3
"""vault_connect_suggest.py — CLI for connect-suggest analytics.

Stage 1: implementations moved to kbai/analytics/connect_suggest.py. This file
is now a thin CLI wrapper that loads the graph, runs all categories via the
new module, renders a markdown report, and writes it to 06-Maps/.

Output: 06-Maps/connect-suggestions.md
"""

from __future__ import annotations

from pathlib import Path

from kbai.analytics.connect_suggest import (
    connect_suggest,
    # re-exported for backward compatibility (other scripts may import these)
    orphan_rescue,
    missing_bidir,
    tag_cluster_gaps,
    force_fit_retype,
    low_centrality_high_substance,
    shared_tags,
    tag_set,
    has_edge_between,
    typed_degree,
)
from vault_graph_loader import VaultGraph

GRAPH_PATH = "06-Maps/vault-graph.json"
OUTPUT_PATH = "06-Maps/connect-suggestions.md"


# ---------------------------------------------------------------------------
# Markdown report (CLI-only — kept here, not in the analytics module)
# ---------------------------------------------------------------------------

def render_markdown(
    orphans: list[dict],
    bidir: list[dict],
    gaps: list[dict],
    retype: list[dict],
    substance: list[dict],
) -> str:
    lines = [
        "# Vault Connect Suggestions",
        "",
        "Auto-generated by `vault_connect_suggest.py` (now a thin CLI over "
        "`kbai/analytics/connect_suggest.py`). Five categories of missing links.",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Category | Count |",
        "|---|---|",
        f"| 1. Orphan rescue | {len(orphans)} |",
        f"| 2. Missing bidirectional | {len(bidir)} |",
        f"| 3. Tag-cluster gaps (3+ shared tags) | {len(gaps)} |",
        f"| 4. Force-fit re-typing (annotation >60 chars) | {len(retype)} |",
        f"| 5. Low-centrality evergreen | {len(substance)} |",
        "",
        "---",
        "",
    ]

    # --- Category 1 ---
    lines += ["## 1. Orphan Rescue", "", "Notes with zero typed edges. Suggestions by shared tag proximity.", ""]
    if orphans:
        lines.append("| Note | Suggested link | Type | Shared tags | Reason |")
        lines.append("|---|---|---|---|---|")
        for r in orphans:
            lines.append(f"| `{r['source']}` | `{r['target']}` | {r['suggested_type']} | {r['confidence']} | {r['reason']} |")
    else:
        lines.append("_No orphans with tag matches found._")
    lines.append("")

    # --- Category 2 ---
    lines += ["---", "", "## 2. Missing Bidirectional Edges", "",
              "A `builds-on` B implies B should have `builds-toward` A, and vice versa.", ""]
    if bidir:
        lines.append("| Add this edge | Type | Because |")
        lines.append("|---|---|---|")
        for r in bidir[:40]:
            lines.append(f"| `{r['source']}` → `{r['target']}` | {r['suggested_type']} | {r['reason']} |")
        if len(bidir) > 40:
            lines.append(f"| _(+{len(bidir) - 40} more)_ | | |")
    else:
        lines.append("_No asymmetries found._")
    lines.append("")

    # --- Category 3 ---
    lines += ["---", "", "## 3. Tag-Cluster Gaps", "",
              "Pairs sharing 3+ tags with no direct edge. Strong `analogous-to` candidates.", ""]
    if gaps:
        lines.append("| Note A | Note B | Shared tags | Reason |")
        lines.append("|---|---|---|---|")
        for r in gaps[:30]:
            lines.append(f"| `{r['source']}` | `{r['target']}` | {r['confidence']} | {r['reason']} |")
        if len(gaps) > 30:
            lines.append(f"| _(+{len(gaps) - 30} more)_ | | | |")
    else:
        lines.append("_No tag-cluster gaps found._")
    lines.append("")

    # --- Category 4 ---
    lines += ["---", "", "## 4. Force-Fit Re-typing Candidates", "",
              "Edges with annotations >60 chars where annotation language suggests a different edge type.", ""]
    if retype:
        lines.append("| Source | Target | Current type | Suggested type | Annotation (truncated) |")
        lines.append("|---|---|---|---|---|")
        for r in retype:
            ann = (r["reason"] or "")[:120].replace("|", "\\|")
            flag = " ⚠️" if r["current_type"] != r["suggested_type"] else ""
            lines.append(
                f"| `{r['source']}` | `{r['target']}` | {r['current_type']}{flag} | {r['suggested_type']} | {ann}… |"
            )
    else:
        lines.append("_No force-fit candidates found._")
    lines.append("")

    # --- Category 5 ---
    lines += ["---", "", "## 5. Low-Centrality High-Substance Notes", "",
              "Evergreen notes with PageRank below the evergreen median. "
              "Well-developed ideas that aren't yet load-bearing in the graph.", ""]
    if substance:
        lines.append("| Note | PageRank | In | Out | Action |")
        lines.append("|---|---|---|---|---|")
        for r in substance:
            parts = r["reason"].split(", ")
            in_out = [p for p in parts if p.startswith("in=") or p.startswith("out=")]
            in_str = in_out[0] if in_out else ""
            out_str = in_out[1] if len(in_out) > 1 else ""
            lines.append(
                f"| `{r['source']}` | {r['confidence']:.5f} | {in_str.replace('in=','')} | "
                f"{out_str.replace('out=','')} | add incoming `analogous-to` or `builds-toward` links |"
            )
    else:
        lines.append("_No low-centrality evergreen notes found._")
    lines.append("")
    lines += ["---", "", "_Generated by `vault_connect_suggest.py`_"]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    g = VaultGraph.load(GRAPH_PATH)
    print("Running all 5 connect-suggest categories…")
    by_cat = connect_suggest(g)
    orphans = by_cat["orphan_rescue"]
    bidir = by_cat["missing_bidir"]
    gaps = by_cat["tag_cluster_gaps"]
    retype = by_cat["force_fit_retype"]
    substance = by_cat["low_centrality_high_substance"]

    print("\nSummary:")
    print(f"  1. Orphan rescue suggestions:       {len(orphans)}")
    print(f"  2. Missing bidirectional edges:     {len(bidir)}")
    print(f"  3. Tag-cluster gaps:                {len(gaps)}")
    print(f"  4. Force-fit re-type candidates:    {len(retype)}")
    print(f"  5. Low-centrality evergreen notes:  {len(substance)}")

    md = render_markdown(orphans, bidir, gaps, retype, substance)
    Path(OUTPUT_PATH).write_text(md, encoding="utf-8")
    print(f"\nWrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
